### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by SteveSizzou** [fja05680/sp500#12]
Hey man, this is so useful! Thank you! Do you by any chance know where I can find the same thing for the S&P100, S&P Midcap 400, and the S&P Smallcap 600? Cheers!

**Comment by fja05680** [comment]
Hi Steve,

Thank you for your kind words.  Getting the current list of these is straight forward.  The indexes can be pulled from the Wikipedia.  I've done this in  separate project:
https://github.com/fja05680/brownbear/tree/master/universe

I'm not aware of any free sources for the historical lists though.  It might be possible to generate it for a few years back using the wiki logs for each.  Otherwise, you have to pay to get these historical lists.

Farrell
