### ISSUE TITLE
only 487 symbols

### ISSUE THREAD

**Issue by hMutzner** [fja05680/sp500#3]
There are 487 symbols in the first row of S&P 500 Historical Components & Changes(04-25-2021).csv
I expected 500. Did the index not always hold 500 symbols?

**Comment by fja05680** [comment]
Hello hMutzner,

It's generally not the case that there are exactly 500 stocks in the S&P500.  Presently, there are 505.  Sometimes there may be a few less than 500 because of the timing of removals from and additions to the index.  That said, I checked and also got 487 symbols for the first row.  It does seem a little low.  This is the original list I got from Andreas Clenow.  It seems to be closer to 500 by the year 2,000.  If this is a concern, perhaps just don't use the first 4 years.  I have no way to independently check it.

**Comment by hMutzner** [comment]
Hello Farrell
Thank you for your elaborate response. There are only very few symbols less than 500. This is not a problem for me. I just wanted to understand.
And thank you for sharing your work. It's the best solution to unfog sp500 history, I found up to now.
Cheers

**Comment by fja05680** [comment]
Great!  And thank you for bringing this to my attention.  I hadn't thought of checking it before.

" It's the best solution to unfog sp500 history, I found up to now."
I believe it's the only free solution, and was happy to share it.  I had been looking myself for quit some time.
